import Link from 'next/link'
import { Button } from '@/components/ui/button'
import {
  BookOpen,
  Sparkles,
  GitBranch,
  MessageSquare,
  Trophy,
  Search,
  Languages,
  ScrollText,
  Columns2,
} from 'lucide-react'

const features = [
  {
    icon: BookOpen,
    title: 'Beautiful reading experience',
    desc: 'Clean, distraction-free layout. Choose from WEB, KJV, or ESV. Adjustable font size, highlight verses in 5 colors, and add personal notes.',
  },
  {
    icon: Sparkles,
    title: 'Instant verse explanations',
    desc: 'Click any verse to get an instant explanation — plain meaning, original context, and theological significance. Powered by Logos, our study companion.',
  },
  {
    icon: GitBranch,
    title: '430,000 cross-references',
    desc: 'Every verse linked to related passages from the Treasury of Scripture Knowledge — the gold standard of biblical cross-referencing. Free, instant, no AI.',
  },
  {
    icon: Languages,
    title: "Strong's Hebrew & Greek",
    desc: "Look up any word's original Hebrew or Greek root — definition, pronunciation, and Strong's number. 8,600 Hebrew + 5,500 Greek entries built-in.",
  },
  {
    icon: ScrollText,
    title: 'Chapter commentary',
    desc: 'Open a chapter commentary for any passage. Generated by Logos the first time, then cached forever — so everyone benefits from the same deep study.',
  },
  {
    icon: Columns2,
    title: 'Side-by-side translations',
    desc: 'Compare WEB, KJV and ESV side by side in the same view. See how different translations render the same passage.',
  },
  {
    icon: MessageSquare,
    title: 'Logos — your study companion',
    desc: 'Ask anything about the passage you\'re reading. Logos knows your current chapter and gives contextual answers from multiple theological traditions.',
  },
  {
    icon: Search,
    title: 'Full-text search',
    desc: 'Search all 31,102 verses by keyword or phrase. Filter by book, Old Testament, or New Testament. Results highlight matching words.',
  },
  {
    icon: Trophy,
    title: 'Streaks, XP & badges',
    desc: 'Build a daily reading habit with streaks and XP. Unlock 15 badges for milestones like completing a book, a 7-day streak, or reaching a new level.',
  },
]

export default function LandingPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      {/* Nav */}
      <header className="sticky top-0 z-40 bg-background/80 backdrop-blur-sm border-b border-border" data-ui>
        <div className="max-w-6xl mx-auto px-4 h-14 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-2xl">✦</span>
            <span className="font-semibold text-lg tracking-tight" style={{ fontFamily: 'system-ui' }}>
              Bible Vibe
            </span>
          </div>
          <div className="flex items-center gap-3" data-ui>
            <Link href="/auth/login">
              <Button variant="ghost" size="sm">Sign in</Button>
            </Link>
            <Link href="/auth/signup">
              <Button size="sm">Get started — it&apos;s free</Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="flex-1 flex flex-col items-center justify-center px-4 py-24 text-center">
        <div
          className="inline-flex items-center gap-2 bg-primary/10 text-primary text-xs font-semibold px-3 py-1.5 rounded-full mb-8"
          style={{ fontFamily: 'system-ui' }}
        >
          <span>✦</span>
          <span>430,000 cross-references · Strong&apos;s concordance · Logos study companion</span>
        </div>

        <h1
          className="text-5xl md:text-7xl font-bold tracking-tight mb-6 max-w-3xl leading-[1.1]"
          style={{ fontFamily: 'Georgia, serif' }}
        >
          The Bible study app
          <br />
          <span className="text-primary">that goes deeper</span>
        </h1>

        <p
          className="text-lg md:text-xl text-muted-foreground mb-10 max-w-2xl leading-relaxed"
          style={{ fontFamily: 'system-ui' }}
        >
          Read any translation. Click any verse for instant explanations, 430K cross-references,
          and original Hebrew &amp; Greek word meanings. Free to use, no account required to start.
        </p>

        <div className="flex flex-col sm:flex-row gap-3" data-ui>
          <Link href="/dashboard/reading/genesis/1">
            <Button size="lg" className="text-base px-8">
              Start reading now
            </Button>
          </Link>
          <Link href="/auth/signup">
            <Button size="lg" variant="outline" className="text-base px-8">
              Create free account
            </Button>
          </Link>
        </div>

        <p className="text-xs text-muted-foreground mt-4" style={{ fontFamily: 'system-ui' }}>
          No credit card · No download · Works in your browser
        </p>
      </section>

      {/* How it works — 3 steps */}
      <section className="py-16 px-4 border-t border-border">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-2xl font-bold text-center mb-2" style={{ fontFamily: 'Georgia, serif' }}>
            How it works
          </h2>
          <p className="text-center text-muted-foreground text-sm mb-12" style={{ fontFamily: 'system-ui' }}>
            Three clicks to go from reading to deep study
          </p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                step: '1',
                title: 'Open any chapter',
                desc: 'Pick any book and chapter. Read in World English Bible, King James, or ESV. Compare two translations side-by-side.',
              },
              {
                step: '2',
                title: 'Tap a verse',
                desc: 'A study panel opens. Highlight it, look up its cross-references, explain it with AI, or search its original Hebrew or Greek word.',
              },
              {
                step: '3',
                title: 'Go as deep as you want',
                desc: 'Open the full chapter commentary, ask Logos a question, save notes, or jump to a cross-referenced passage.',
              },
            ].map((s) => (
              <div key={s.step} className="flex gap-4">
                <div className="w-8 h-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-sm font-bold shrink-0 mt-0.5">
                  {s.step}
                </div>
                <div>
                  <h3 className="font-semibold mb-1" style={{ fontFamily: 'system-ui' }}>{s.title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed" style={{ fontFamily: 'system-ui' }}>{s.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features grid */}
      <section className="py-20 px-4 bg-secondary/30 border-t border-border">
        <div className="max-w-6xl mx-auto">
          <h2
            className="text-3xl md:text-4xl font-bold text-center mb-4"
            style={{ fontFamily: 'Georgia, serif' }}
          >
            Everything built in
          </h2>
          <p className="text-center text-muted-foreground mb-12 max-w-xl mx-auto" style={{ fontFamily: 'system-ui' }}>
            Every feature below is live and working right now — no paywalls, no waitlists.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {features.map((f) => (
              <div
                key={f.title}
                className="bg-card rounded-xl p-5 border border-border hover:border-primary/40 transition-colors"
              >
                <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center mb-3">
                  <f.icon className="w-5 h-5 text-primary" />
                </div>
                <h3 className="font-semibold text-sm mb-1.5" style={{ fontFamily: 'system-ui' }}>
                  {f.title}
                </h3>
                <p className="text-xs text-muted-foreground leading-relaxed" style={{ fontFamily: 'system-ui' }}>
                  {f.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-4 text-center border-t border-border">
        <h2 className="text-3xl md:text-4xl font-bold mb-4" style={{ fontFamily: 'Georgia, serif' }}>
          Start studying in seconds
        </h2>
        <p className="text-muted-foreground mb-8 max-w-md mx-auto" style={{ fontFamily: 'system-ui' }}>
          No account needed to read. Create a free account to save highlights, notes, bookmarks, and track your progress.
        </p>
        <div className="flex flex-col sm:flex-row gap-3 justify-center">
          <Link href="/dashboard/reading/john/1">
            <Button size="lg" className="text-base px-8">Read John 1 now</Button>
          </Link>
          <Link href="/auth/signup">
            <Button size="lg" variant="outline" className="text-base px-8">Create free account</Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border py-6 px-4" data-ui>
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-2 text-xs text-muted-foreground" style={{ fontFamily: 'system-ui' }}>
          <div className="flex items-center gap-1.5">
            <span>✦</span>
            <span>Bible Vibe</span>
          </div>
          <p>World English Bible and KJV are public domain. Strong&apos;s concordance via Open Scriptures (CC-BY-SA).</p>
        </div>
      </footer>
    </div>
  )
}
