import Link from 'next/link'
import { Button } from '@/components/ui/button'
import {
  BookOpen, Sparkles, GitBranch, MessageSquare,
  Trophy, Search, Languages, ScrollText, Columns2, ArrowRight, Zap,
} from 'lucide-react'

const features = [
  { icon: Sparkles,     title: 'Ezra AI study companion',      desc: "Ask anything about the passage you're reading. Ezra gives contextual answers rooted in theology, history, and the original languages." },
  { icon: GitBranch,    title: '430,000 cross-references',      desc: 'Every verse linked to related passages from the Treasury of Scripture Knowledge — the gold standard of biblical cross-referencing.' },
  { icon: Languages,    title: 'Hebrew & Greek interlinear',    desc: "See every word in its original language inline — definition, pronunciation, and Strong's number. 8,600 Hebrew + 5,500 Greek entries." },
  { icon: ScrollText,   title: 'Chapter commentary',            desc: 'Deep commentary for any chapter — generated by Ezra, cached for everyone. Theological, historical, and practical perspectives.' },
  { icon: Columns2,     title: 'Side-by-side translations',     desc: 'Compare ESV, BSB, WEB and KJV simultaneously. See how different scholars render the same passage.' },
  { icon: BookOpen,     title: 'Reading plans',                 desc: 'Guided plans from the whole Bible to targeted studies. Paced to your schedule, tracked automatically.' },
  { icon: MessageSquare,title: 'Bible quiz',                    desc: 'Test your understanding of any passage, book, or topic. Write your own or let Ezra generate one instantly.' },
  { icon: Search,       title: 'Full-text search',              desc: 'Search all 31,102 verses by keyword or phrase. Filter by book, Old or New Testament.' },
  { icon: Trophy,       title: 'Streaks, XP & badges',          desc: 'Build a daily reading habit. Earn XP, unlock 15 achievement badges, and track your progress over time.' },
]

function KairosWordmark() {
  return (
    <div className="flex items-center gap-2.5">
      <div
        className="w-8 h-8 rounded-sm border border-primary/60 flex items-center justify-center text-primary font-bold text-xl shrink-0 bg-primary/5"
        style={{ fontFamily: 'var(--font-cormorant), Georgia, serif', letterSpacing: '-0.02em' }}
      >
        K
      </div>
      <span
        className="font-semibold tracking-wide text-foreground"
        style={{ fontFamily: 'var(--font-cormorant), Georgia, serif', fontSize: '1.2rem', letterSpacing: '0.08em' }}
      >
        KAIROS
      </span>
    </div>
  )
}

function OrnamentDivider({ label }: { label?: string }) {
  return (
    <div className="ornament-rule text-xs font-medium tracking-widest uppercase text-primary/50 my-1"
      style={{ fontFamily: 'var(--font-inter), system-ui' }}>
      {label && <span>{label}</span>}
    </div>
  )
}

export default function LandingPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">

      {/* Nav */}
      <header className="sticky top-0 z-40 bg-background/90 backdrop-blur-sm border-b border-border" data-ui>
        <div className="max-w-5xl mx-auto px-6 h-14 flex items-center justify-between">
          <KairosWordmark />
          <div className="flex items-center gap-3" data-ui>
            <Link href="/auth/login">
              <Button variant="ghost" size="sm" className="text-muted-foreground hover:text-foreground">Sign in</Button>
            </Link>
            <Link href="/auth/signup">
              <Button size="sm" className="gap-1.5 bg-primary hover:bg-primary/90 text-primary-foreground">
                Begin free <ArrowRight className="w-3 h-3" />
              </Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="relative flex flex-col items-center justify-center px-6 pt-28 pb-24 text-center overflow-hidden">
        {/* Subtle radial glow */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[500px] h-[400px] bg-primary/6 rounded-full blur-[80px] pointer-events-none" />

        <div className="relative max-w-3xl">
          {/* Eyebrow */}
          <p
            className="text-xs tracking-[0.25em] uppercase text-primary/70 mb-8 font-medium"
            style={{ fontFamily: 'var(--font-inter), system-ui' }}
          >
            Scripture. Depth. Clarity.
          </p>

          {/* Headline — Cormorant large */}
          <h1
            className="text-6xl md:text-8xl font-light text-foreground mb-4 leading-[1.02]"
            style={{ fontFamily: 'var(--font-cormorant), Georgia, serif', fontWeight: 300 }}
          >
            Your moment
          </h1>
          <h1
            className="text-6xl md:text-8xl font-semibold text-primary mb-10 leading-[1.02]"
            style={{ fontFamily: 'var(--font-cormorant), Georgia, serif' }}
          >
            in the Word.
          </h1>

          <p
            className="text-base md:text-lg text-muted-foreground mb-12 max-w-xl mx-auto leading-relaxed"
            style={{ fontFamily: 'var(--font-inter), system-ui' }}
          >
            Kairos is the all-in-one Bible study tool — built for those who want to understand Scripture in its historical and cultural context. Ancient Near East background, 430K cross-references, commentary. All in one place.
          </p>

          <div className="flex flex-col sm:flex-row gap-3 justify-center" data-ui>
            <Link href="/auth/signup">
              <Button size="lg" className="h-11 px-8 text-sm tracking-wide bg-primary hover:bg-primary/90 text-primary-foreground">
                BEGIN YOUR STUDY
              </Button>
            </Link>
            <Link href="/auth/login">
              <Button size="lg" variant="outline" className="h-11 px-8 text-sm tracking-wide border-border hover:bg-muted">
                SIGN IN
              </Button>
            </Link>
          </div>

          <p className="text-xs text-muted-foreground/60 mt-5 tracking-wide" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
            Free account · No download · Cancel anytime
          </p>
        </div>
      </section>

      {/* Brand verse + name meaning */}
      <section className="py-20 px-6 border-t border-border">
        <div className="max-w-2xl mx-auto text-center space-y-6">
          <OrnamentDivider label="καιρός" />

          {/* Name meaning */}
          <div className="space-y-3">
            <h2
              className="text-4xl md:text-5xl font-light text-foreground"
              style={{ fontFamily: 'var(--font-cormorant), Georgia, serif' }}
            >
              Why <em>Kairos</em>?
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed max-w-lg mx-auto" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
              Ancient Greek has two words for time. <strong className="text-foreground">Χρόνος</strong> (chronos) is the clock — seconds ticking by, calendars filling up. But <strong className="text-foreground">καιρός</strong> (kairos) is something different entirely: the <em>appointed moment</em>. The right time. A moment charged with meaning and purpose.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed max-w-lg mx-auto" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
              Every time you open Scripture, it&apos;s not just another minute in the day. It&apos;s a kairos — an opportunity to encounter the living God. This app exists to help you make the most of those moments.
            </p>
          </div>

          <OrnamentDivider />

          <blockquote
            className="text-2xl md:text-3xl font-light leading-relaxed text-foreground/80 italic pt-2"
            style={{ fontFamily: 'var(--font-lora), Georgia, serif' }}
          >
            "See then that ye walk circumspectly, not as fools, but as wise,{' '}
            <span className="text-primary not-italic font-medium">redeeming the time</span> —
            for the days are evil."
          </blockquote>
          <p className="text-xs tracking-widest uppercase text-muted-foreground font-medium"
            style={{ fontFamily: 'var(--font-inter), system-ui' }}>
            Ephesians 5:15–16 · &ldquo;the time&rdquo; = <em>καιρός</em>
          </p>

          <OrnamentDivider />
        </div>
      </section>

      {/* Stats */}
      <section className="py-16 px-6 bg-secondary/40 border-t border-border">
        <div className="max-w-3xl mx-auto grid grid-cols-3 gap-6 text-center">
          {[
            { value: '31,102', label: 'Verses' },
            { value: '430,000', label: 'Cross-references' },
            { value: '14,100', label: 'Hebrew & Greek words' },
          ].map((s) => (
            <div key={s.label}>
              <p
                className="text-3xl md:text-4xl font-semibold text-primary"
                style={{ fontFamily: 'var(--font-cormorant), Georgia, serif' }}
              >
                {s.value}
              </p>
              <p
                className="text-xs tracking-widest uppercase text-muted-foreground mt-1"
                style={{ fontFamily: 'var(--font-inter), system-ui' }}
              >
                {s.label}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section className="py-20 px-6 border-t border-border">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-14">
            <p className="text-xs tracking-[0.2em] uppercase text-primary/60 mb-3" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
              How it works
            </p>
            <h2 className="text-3xl md:text-4xl font-light" style={{ fontFamily: 'var(--font-cormorant), Georgia, serif' }}>
              From passage to understanding
              <br />
              <span className="text-primary font-semibold">in seconds.</span>
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
            {[
              { num: 'I',   title: 'Open any passage',     desc: 'Pick any book and chapter. Read in ESV, BSB, KJV, or WEB. Compare two translations side-by-side.' },
              { num: 'II',  title: 'Tap any verse',         desc: 'A study panel opens instantly — cross-references, original language, AI explanation, highlight, note.' },
              { num: 'III', title: 'Go as deep as you want',desc: 'Ask Ezra a question. Open the full commentary. Jump to a cross-reference. Save notes.' },
            ].map((s) => (
              <div key={s.num} className="space-y-3">
                <p
                  className="text-5xl font-light text-primary/20 leading-none"
                  style={{ fontFamily: 'var(--font-cormorant), Georgia, serif' }}
                >
                  {s.num}
                </p>
                <div className="w-8 h-px bg-primary/40" />
                <h3 className="font-medium text-sm tracking-wide" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
                  {s.title}
                </h3>
                <p className="text-sm text-muted-foreground leading-relaxed" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
                  {s.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-20 px-6 bg-secondary/40 border-t border-border">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14">
            <p className="text-xs tracking-[0.2em] uppercase text-primary/60 mb-3" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
              Everything included
            </p>
            <h2 className="text-3xl md:text-4xl font-light" style={{ fontFamily: 'var(--font-cormorant), Georgia, serif' }}>
              A seminary library.
              <br />
              <span className="text-primary font-semibold">In your pocket.</span>
            </h2>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {features.map((f) => (
              <div
                key={f.title}
                className="bg-card border border-border rounded p-5 hover:border-primary/50 hover:shadow-sm transition-all group"
              >
                <div className="w-8 h-8 rounded-sm bg-primary/8 border border-primary/15 flex items-center justify-center mb-4 group-hover:bg-primary/12 transition-colors">
                  <f.icon className="w-4 h-4 text-primary" />
                </div>
                <h3 className="font-medium text-sm mb-1.5" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
                  {f.title}
                </h3>
                <p className="text-xs text-muted-foreground leading-relaxed" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
                  {f.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="py-20 px-6 border-t border-border">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-xs tracking-[0.2em] uppercase text-primary/60 mb-3" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
              Pricing
            </p>
            <h2 className="text-3xl md:text-4xl font-light" style={{ fontFamily: 'var(--font-cormorant), Georgia, serif' }}>
              Free to study.
              <span className="text-primary font-semibold"> Pro to go deeper.</span>
            </h2>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* Free */}
            <div className="bg-card border border-border rounded p-6 space-y-5">
              <div>
                <p className="text-xs tracking-widest uppercase text-muted-foreground mb-1" style={{ fontFamily: 'var(--font-inter), system-ui' }}>Free</p>
                <p className="text-4xl font-light" style={{ fontFamily: 'var(--font-cormorant), Georgia, serif' }}>$0</p>
              </div>
              <div className="h-px bg-border" />
              <ul className="space-y-2.5">
                {['All 4 translations', 'Highlights & notes', '20 Ezra messages / day', 'Reading plans', 'Bible quiz', 'Streaks & XP'].map(f => (
                  <li key={f} className="flex items-center gap-2.5 text-sm text-muted-foreground" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
                    <span className="w-1 h-1 rounded-full bg-primary/50 shrink-0" />
                    {f}
                  </li>
                ))}
              </ul>
              <Link href="/auth/signup">
                <Button variant="outline" className="w-full text-xs tracking-widest uppercase h-10">
                  Get started free
                </Button>
              </Link>
            </div>

            {/* Pro */}
            <div className="bg-foreground rounded p-6 space-y-5 text-background">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <p className="text-xs tracking-widest uppercase text-background/60" style={{ fontFamily: 'var(--font-inter), system-ui' }}>Pro</p>
                  <span className="text-[10px] bg-primary text-primary-foreground px-2 py-0.5 rounded-sm font-medium tracking-wide uppercase" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
                    Most popular
                  </span>
                </div>
                <p className="text-4xl font-light text-background" style={{ fontFamily: 'var(--font-cormorant), Georgia, serif' }}>
                  $9.99<span className="text-xl opacity-50"> / mo</span>
                </p>
                <p className="text-xs opacity-40 mt-0.5" style={{ fontFamily: 'var(--font-inter), system-ui' }}>or $89 / year · save 26%</p>
              </div>
              <div className="h-px bg-background/10" />
              <ul className="space-y-2.5">
                {['Everything in Free', 'Unlimited Ezra conversations', 'Scholar mode — deep theology', 'Interlinear Hebrew & Greek view', 'Priority response speed', 'Sermon prep tools (coming soon)'].map(f => (
                  <li key={f} className="flex items-center gap-2.5 text-sm text-background/80" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
                    <Zap className="w-3 h-3 text-primary shrink-0" />
                    {f}
                  </li>
                ))}
              </ul>
              <Link href="/auth/signup">
                <Button className="w-full text-xs tracking-widest uppercase h-10 bg-primary hover:bg-primary/90 text-primary-foreground">
                  Begin Pro — 33¢ / day
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-28 px-6 text-center border-t border-border bg-secondary/30 relative overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[400px] h-[300px] bg-primary/5 rounded-full blur-[60px] pointer-events-none" />
        <div className="relative max-w-xl mx-auto space-y-6">
          <p className="text-xs tracking-[0.25em] uppercase text-primary/60" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
            Begin today
          </p>
          <h2
            className="text-4xl md:text-5xl font-light leading-tight text-foreground"
            style={{ fontFamily: 'var(--font-cormorant), Georgia, serif' }}
          >
            Your kairos moment
            <br />
            <span className="text-primary font-semibold">starts now.</span>
          </h2>
          <p className="text-muted-foreground text-sm leading-relaxed" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
            Create a free account to start reading, save highlights and notes,
            track your progress, and go deeper with AI.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center pt-2" data-ui>
            <Link href="/auth/signup">
              <Button size="lg" className="h-11 px-10 text-sm tracking-widest uppercase bg-primary hover:bg-primary/90 text-primary-foreground">
                Start for free
              </Button>
            </Link>
            <Link href="/auth/login">
              <Button size="lg" variant="outline" className="h-11 px-10 text-sm tracking-wide border-border">
                Sign in
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border py-8 px-6" data-ui>
        <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <KairosWordmark />
          <p className="text-xs text-muted-foreground/50 text-center sm:text-right" style={{ fontFamily: 'var(--font-inter), system-ui' }}>
            WEB & KJV are public domain · ESV used with permission · Strong&apos;s via Open Scriptures CC-BY-SA
          </p>
        </div>
      </footer>
    </div>
  )
}
