import { notFound } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { BIBLE_BOOKS } from '@/lib/bible-data'
import { Card } from '@/components/ui/card'
import { ChevronRight, BookOpen, User, Calendar, Users, Target, Sparkles } from 'lucide-react'
import { generateBookOverview } from '@/lib/claude'

interface Props {
  params: Promise<{ book: string }>
}

export default async function BookOverviewPage({ params }: Props) {
  const { book: bookSlug } = await params

  const bookMeta = BIBLE_BOOKS.find(
    (b) => b.name.toLowerCase().replace(/\s+/g, '-') === bookSlug
  )
  if (!bookMeta) notFound()

  const supabase = await createClient()

  // Try to fetch existing overview
  let { data: overview } = await supabase
    .from('book_overviews')
    .select('*')
    .eq('book_id', bookMeta.id)
    .single()

  // If no overview exists, generate one via Claude and cache it
  if (!overview) {
    const generated = await generateBookOverview(bookMeta.name, bookMeta.testament)
    if (generated) {
      const { data: inserted } = await supabase
        .from('book_overviews')
        .insert({
          book_id: bookMeta.id,
          author:       generated.author,
          date_written: generated.date_written,
          audience:     generated.audience,
          purpose:      generated.purpose,
          key_themes:   generated.key_themes,
          outline:      generated.outline,
          key_verses:   generated.key_verses,
          summary:      generated.summary,
        })
        .select()
        .single()
      overview = inserted
    }
  }

  const outline: { range: string; title: string }[] = overview?.outline ?? []
  const keyVerses: { ref: string; text: string }[] = overview?.key_verses ?? []
  const themes: string[] = overview?.key_themes ?? []

  return (
    <div className="max-w-3xl mx-auto px-4 py-8">
      {/* Back */}
      <Link
        href={`/dashboard/reading/${bookSlug}/1`}
        className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground mb-6 transition-colors"
        style={{ fontFamily: 'system-ui' }}
      >
        <ChevronRight className="w-3 h-3 rotate-180" />
        Read {bookMeta.name}
      </Link>

      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
          <BookOpen className="w-5 h-5 text-primary" />
        </div>
        <div>
          <h1 className="text-3xl font-bold" style={{ fontFamily: 'var(--font-cormorant), Georgia, serif' }}>
            {bookMeta.name}
          </h1>
          <p className="text-sm text-muted-foreground" style={{ fontFamily: 'system-ui' }}>
            Book Overview · {bookMeta.chapters} chapters · {bookMeta.testament} Testament
          </p>
        </div>
      </div>

      {!overview ? (
        <div className="text-center py-16">
          <p className="text-muted-foreground text-sm" style={{ fontFamily: 'system-ui' }}>
            Overview could not be generated right now. Try again shortly.
          </p>
        </div>
      ) : (
        <div className="space-y-6">

          {/* AI badge */}
          {overview && (
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground/60" style={{ fontFamily: 'system-ui' }}>
              <Sparkles className="w-3 h-3" />
              Generated by Ezra AI · cached for fast access
            </div>
          )}

          {/* Summary */}
          {overview?.summary && (
            <p className="text-base leading-relaxed text-muted-foreground italic"
              style={{ fontFamily: 'var(--font-cormorant), Georgia, serif' }}>
              {overview.summary}
            </p>
          )}

          {/* 4 meta cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {[
              { icon: User,     label: 'Author',        value: overview.author },
              { icon: Calendar, label: 'Date Written',   value: overview.date_written },
              { icon: Users,    label: 'Audience',       value: overview.audience },
              { icon: Target,   label: 'Purpose',        value: overview.purpose },
            ].map(({ icon: Icon, label, value }) => (
              <Card key={label} className="p-4 border-border">
                <div className="flex items-start gap-2">
                  <Icon className="w-3.5 h-3.5 text-muted-foreground mt-0.5 shrink-0" />
                  <div>
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1" style={{ fontFamily: 'system-ui' }}>
                      {label}
                    </p>
                    <p className="text-sm" style={{ fontFamily: 'system-ui' }}>{value}</p>
                  </div>
                </div>
              </Card>
            ))}
          </div>

          {/* Key Themes */}
          {themes.length > 0 && (
            <div>
              <h2 className="text-sm font-semibold mb-3" style={{ fontFamily: 'system-ui' }}>
                Key Themes
              </h2>
              <div className="flex flex-wrap gap-2">
                {themes.map((theme) => (
                  <span
                    key={theme}
                    className="text-xs bg-secondary text-secondary-foreground px-3 py-1.5 rounded-full"
                    style={{ fontFamily: 'system-ui' }}
                  >
                    {theme}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Book Outline */}
          {outline.length > 0 && (
            <div>
              <h2 className="text-sm font-semibold mb-3" style={{ fontFamily: 'system-ui' }}>
                Book Outline
              </h2>
              <Card className="border-border divide-y divide-border">
                {outline.map((section, i) => {
                  const chapter = parseInt(section.range.split(':')[0]) || 1
                  return (
                    <Link
                      key={i}
                      href={`/dashboard/reading/${bookSlug}/${chapter}`}
                      className="flex items-center justify-between px-4 py-3 hover:bg-muted/40 transition-colors group"
                    >
                      <div className="flex items-center gap-4">
                        <span className="text-xs text-muted-foreground w-16 shrink-0 font-mono">
                          {section.range}
                        </span>
                        <span className="text-sm group-hover:text-primary transition-colors" style={{ fontFamily: 'system-ui' }}>
                          {section.title}
                        </span>
                      </div>
                      <ChevronRight className="w-3.5 h-3.5 text-muted-foreground shrink-0" />
                    </Link>
                  )
                })}
              </Card>
            </div>
          )}

          {/* Key Verses */}
          {keyVerses.length > 0 && (
            <div>
              <h2 className="text-sm font-semibold mb-3" style={{ fontFamily: 'system-ui' }}>
                Key Verses
              </h2>
              <Card className="border-border divide-y divide-border">
                {keyVerses.map((kv, i) => {
                  const chapter = parseInt(kv.ref.split(':')[0]) || 1
                  return (
                    <Link
                      key={i}
                      href={`/dashboard/reading/${bookSlug}/${chapter}`}
                      className="flex items-center gap-4 px-4 py-3 hover:bg-muted/40 transition-colors group"
                    >
                      <span className="text-xs text-primary font-semibold w-12 shrink-0" style={{ fontFamily: 'system-ui' }}>
                        {kv.ref}
                      </span>
                      <span className="text-sm text-muted-foreground italic flex-1 line-clamp-2 group-hover:text-foreground transition-colors" style={{ fontFamily: 'var(--font-cormorant), Georgia, serif' }}>
                        {kv.text}
                      </span>
                    </Link>
                  )
                })}
              </Card>
            </div>
          )}

          {/* Read CTA */}
          <Link href={`/dashboard/reading/${bookSlug}/1`}>
            <Card className="p-4 border-primary/20 bg-primary/5 hover:border-primary/40 transition-colors flex items-center justify-between">
              <div>
                <p className="text-sm font-semibold" style={{ fontFamily: 'system-ui' }}>
                  Start reading {bookMeta.name}
                </p>
                <p className="text-xs text-muted-foreground mt-0.5" style={{ fontFamily: 'system-ui' }}>
                  Chapter 1 of {bookMeta.chapters}
                </p>
              </div>
              <ChevronRight className="w-4 h-4 text-primary shrink-0" />
            </Card>
          </Link>
        </div>
      )}
    </div>
  )
}
